--**************************************************** 5.MAGNITUDE EXPLORATION ************************************************************



-- Total Customer count by countries:
select country, COUNT(customer_key) as total_customers from Gold.dim_customers GROUP BY country ORDER BY total_customers DESC

-- total customers by gender:
select gender, count(*) from Gold.dim_customers group by gender
-- OR
select gender, count(customer_key) from Gold.dim_customers group by gender

-- find total products by category:
select category, count(category_id) from Gold.dim_products group by category order by category
select category, count(*) from Gold.dim_products group by category order by category

-- average cost in each category:
select category, avg(product_cost) as Average_cost from Gold.dim_products group by category order by Average_cost DESC

-- total revenue generated for each category:
select aa.category, CAST(sum(ab.sales_amount)AS nvarchar) + ' Rs' as total_sales from gold.dim_products aa
RIGHT JOIN gold.fact_sales ab
ON aa.product_key = ab.product_key
GROUP BY aa.category
ORDER BY sum(ab.sales_amount) DESC

-- total revenue generated by each customer:
select ba.first_name + ' '+ ba.last_name , sum(bb.sales_amount) as total_revenue
from Gold.fact_sales bb
LEFT JOIN Gold.dim_customers ba
ON bb.customer_key = ba.customer_key
GROUP BY bb.customer_key,ba.first_name,ba.last_name
ORDER BY total_revenue DESC

-- distribution of sold items across countries:
select ca.country, sum(cc.quantity) as total_sold_items
from Gold.fact_sales cc
LEFT JOIN Gold.dim_customers ca
ON cc.customer_key = ca.customer_key
GROUP BY ca.country
ORDER BY total_sold_items DESC

